# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  dev:
    desc: "Run the application with auto-restart on file changes"
    cmds:
      - uv run watchmedo auto-restart --recursive --pattern="*.py" --directory="./src" uv run python -- -m src.grpc_server
